# SITE SETTINGS
title: Wildlife Malaria Network
# author: 
baseurl: "/web"

# SOCIAL PROFILES
social:
#  email: 
#  twitter: 
#  github: 

# THEME SETTINGS
theme: minima # Fallback theme
remote_theme: peterdesmet/petridish@3.0
posts_on_home: 4
tweets_on_home: false
archive_permalink: /news/
github_edit: true
logo: assets/images/logo-nav.png
colors:
  links: "#660000"
  banner: "#990000"
  footer: "#660000"

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      type: "posts"
    values:
      permalink: "/news/:year/:slug/"
